# NumPy Basics: Arrays and Vectorized Computation

## NumPy基礎：矩陣與向量計算

NumPy是高效能科學計算數據分析的基礎函式庫，也是本書所介紹所有的高級工具的建構基礎，其部分功能如下:

* ndarray 具有向量計算與複雜的廣播功能(?!)快速且節省空間的多維陣列
* 可對於整組數據做快速計算，不須迴圈
* 讀寫檔案，與操作記憶體內檔案的工具
* 線性代數 亂數 傅立葉轉換功能
* 用C、C++、fortran編寫的工具

In [1]:
#繪圖顯示在ipython之中
%matplotlib inline

In [2]:
#匯入套件
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

### 多維度的陣列物件，物件內item必須為相同型態

In [4]:
#產生一個2x3的亂數陣列
data = randn(2, 3)
print(data)

[[ 1.4878  0.0488  0.4539]
 [ 0.0047 -0.4324 -0.9508]]


In [5]:
print(data * 10)
print(data + data)

[[ 14.8784   0.4876   4.5388]
 [  0.0469  -4.3242  -9.5077]]
[[ 2.9757  0.0975  0.9078]
 [ 0.0094 -0.8648 -1.9015]]


In [7]:
#顯示維度與型態
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays
#### 建立陣列物件

In [9]:
#建立一維陣列
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
#建立二維陣列
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [12]:
#會自動判斷最適合的型別
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [14]:
print('一維0矩陣')
print(np.zeros(10))
print('二維0矩陣')
print(np.zeros((3, 6)))
print('三維空矩陣')
print(np.empty((2, 3, 2)))

一維0矩陣
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
二維0矩陣
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
三維空矩陣
[[[  1.4005e-311   6.3660e-314]
  [  0.0000e+000   2.9644e-323]
  [  1.9098e-313   8.9334e+165]]

 [[  5.2660e-037   3.2255e-313]
  [  1.1167e+165   4.0318e-313]
  [  1.0414e-071   1.4213e+161]]]


In [18]:
print(np.arange(15))
print(np.arange(0, 10, 0.5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]


|函數名稱|說明|
|--|--|
|array|將輸入數據轉換成ndarray，預設值接複製輸入數字|
|asarray|將輸入數據轉換成ndarray，如果輸入本身就是ndarray就不進行複製|
|arange|類似內建的range，但是是ndarray物件不是list|
|ones|產生皆為1的陣列|
|zeros|產生皆為0的陣列|
|empty|產生空陣列|
|eye、identity|產生單元矩陣|

### Data Types for ndarrays
#### ndarray的數據類型

|類型|類型代碼|說明|
|--|--|--|
|int8, uint8|i1, u1|有正負和無正負的8位整數|
|int16, uint16|i2, u2|有正負和無正負的16位整數|
|int32, uint32|i4, u4|有正負和無正負的32位整數|
|int64, uint64|i8, u8|有正負和無正負的64位整數|
|float16|f2|半精度浮點數|
|float32|f4 or f|標準單精度浮點數|
|float64|f8 or d|標準雙精度浮點數|
|float128|f16 or g|擴展精度浮點數|
|complex64, complex128, complex256|c8, c16, c32|複數|
|bool|?|True與False|
|object|O|Python的物件|
|string\_|S|固定長度的字串，如S10表示10個字節的文字|
|unicode\_|U|固定長度的unicode類型，如U10表示10個字節的文字|


In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [23]:
#強迫轉換浮點數至整數，則小數部分捨去
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [24]:
#轉換文字至浮點數
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [26]:
#使用代碼宣告類型
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

### Operations between arrays and scalars
#### 矩陣之間的運算

只要維度與大小相同的矩陣，任何運算皆會直接套用至每一個元素

In [4]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print('平方')
print(arr * arr)
print('相減')
print(arr - arr)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
平方
[[  1.   4.   9.]
 [ 16.  25.  36.]]
相減
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [5]:
print('倒數')
print(1 / arr)
print('開根號')
print(arr ** 0.5)

倒數
[[ 1.      0.5     0.3333]
 [ 0.25    0.2     0.1667]]
開根號
[[ 1.      1.4142  1.7321]
 [ 2.      2.2361  2.4495]]


### Basic indexing and slicing
#### 矩陣索引與拆解

In [10]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])

# 廣播用法，範圍內皆取代
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [11]:
#傳址，原始數據會受影響
arr_slice = arr[5:8]
arr_slice[1] = 12345
print(arr)
arr_slice[:] = 64
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


矩陣數據排列方式
![ss](http://i.imgur.com/ORBaVai.png)

In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [14]:
print(arr2d[0][2])
print(arr2d[0, 2]) #結果同上

3
3


In [15]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
old_values = arr3d[0].copy() #傳值
#改變原始數據
arr3d[0] = 42
print(arr3d)

print('=====================')
#把剛剛copy的數據放回去，可以證明copy傳值不傳址
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
arr3d[1, 0]

array([7, 8, 9])

#### Indexing with slices
#### 索引用法，與原生list差不多

In [22]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [23]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [24]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [25]:
print(arr2d[1, :2])
print(arr2d[2, :1])

[4 5]
[7]


In [26]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [28]:
arr2d[:2, 1:] = 0
print(arr2d)

[[1 0 0]
 [4 0 0]
 [7 8 9]]


### Boolean indexing
#### 布林值索引

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.4441  1.3117  0.8441 -0.551 ]
 [ 0.2886 -1.2667 -1.1664  0.0515]
 [-0.5104 -0.7043  0.6989 -0.5112]
 [-0.5506 -0.8117 -0.3238 -0.228 ]
 [ 0.3235 -1.0718  1.0411 -0.3923]
 [-1.1307  1.0547  0.4029 -2.3839]
 [ 0.593   0.6497  0.068  -0.5722]]


In [30]:
#判斷哪幾項為Bob
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [31]:
#利用bool來塞選舉陣
data[names == 'Bob']

array([[ 0.4441,  1.3117,  0.8441, -0.551 ],
       [-0.5506, -0.8117, -0.3238, -0.228 ]])

In [39]:
#可再配合slices指定範圍
print(data[names == 'Bob', 2:])
print(data[names == 'Bob', 3])

[[ 0.8441 -0.551 ]
 [-0.3238 -0.228 ]]
[-0.551 -0.228]


In [41]:
#可用!=找到相反的，或是~取得相反結果
print(names != 'Bob')
data[~(names == 'Bob')]

[False  True  True False  True  True  True]


array([[ 0.2886, -1.2667, -1.1664,  0.0515],
       [-0.5104, -0.7043,  0.6989, -0.5112],
       [ 0.3235, -1.0718,  1.0411, -0.3923],
       [-1.1307,  1.0547,  0.4029, -2.3839],
       [ 0.593 ,  0.6497,  0.068 , -0.5722]])

In [38]:
#使用or選取多個條件
mask = (names == 'Bob') | (names == 'Will')
print(mask)
data[mask]

[ True False  True  True  True False False]


array([[ 0.4441,  1.3117,  0.8441, -0.551 ],
       [-0.5104, -0.7043,  0.6989, -0.5112],
       [-0.5506, -0.8117, -0.3238, -0.228 ],
       [ 0.3235, -1.0718,  1.0411, -0.3923]])

In [42]:
#使用數字篩選
data[data < 0] = 0
data

array([[ 0.4441,  1.3117,  0.8441,  0.    ],
       [ 0.2886,  0.    ,  0.    ,  0.0515],
       [ 0.    ,  0.    ,  0.6989,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3235,  0.    ,  1.0411,  0.    ],
       [ 0.    ,  1.0547,  0.4029,  0.    ],
       [ 0.593 ,  0.6497,  0.068 ,  0.    ]])

In [43]:
#使用文字篩選
data[names != 'Joe'] = 7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.2886,  0.    ,  0.    ,  0.0515],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  1.0547,  0.4029,  0.    ],
       [ 0.593 ,  0.6497,  0.068 ,  0.    ]])

### Fancy indexing
#### 花式索引

In [44]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [45]:
#可根據索引重新排列陣列
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [46]:
#負數表示從後面數過來
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [47]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
print(arr)

#取得此索引位置的值，重新排成矩陣(1,0) (5,3) (7,1) (2,2)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [48]:
#取得特定行，並重新排列每一行元素位置
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [49]:
#結果同上，轉換兩個亦為矩陣成選取區域
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing arrays and swapping axes
#### 轉置與軸對換

In [50]:
arr = np.arange(15).reshape((3, 5))
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [51]:
arr = np.random.randn(6, 3)
print(arr)
np.dot(arr.T, arr)

[[ 0.731   0.131   1.5827]
 [ 1.3226 -0.2932 -1.1494]
 [ 0.52    0.1692 -1.9393]
 [-1.4068 -1.2761  0.9021]
 [ 0.928  -0.0219 -0.1956]
 [-1.8882 -1.0603  0.3587]]


array([[ 8.9596,  3.5729, -3.4994],
       [ 3.5729,  2.885 , -1.311 ],
       [-3.4994, -1.311 ,  8.5675]])

In [54]:
arr = np.arange(24).reshape((2, 3, 4))
print(arr)
arr.transpose((2, 1, 0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))