# NumPy Basics: Arrays and Vectorized Computation

## NumPy基礎：矩陣與向量計算

NumPy是高效能科學計算數據分析的基礎函式庫，也是本書所介紹所有的高級工具的建構基礎，其部分功能如下:

* ndarray 具有向量計算與複雜的廣播功能(?!)快速且節省空間的多維陣列
* 可對於整組數據做快速計算，不須迴圈
* 讀寫檔案，與操作記憶體內檔案的工具
* 線性代數 亂數 傅立葉轉換功能
* 用C、C++、fortran編寫的工具

In [1]:
#繪圖顯示在ipython之中
%matplotlib inline

In [3]:
#匯入套件
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

### 多維度的陣列物件，物件內item必須為相同型態

In [4]:
#產生一個2x3的亂數陣列
data = randn(2, 3)
print(data)

[[ 1.4878  0.0488  0.4539]
 [ 0.0047 -0.4324 -0.9508]]


In [5]:
print(data * 10)
print(data + data)

[[ 14.8784   0.4876   4.5388]
 [  0.0469  -4.3242  -9.5077]]
[[ 2.9757  0.0975  0.9078]
 [ 0.0094 -0.8648 -1.9015]]


In [7]:
#顯示維度與型態
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays
#### 建立陣列物件

In [9]:
#建立一維陣列
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
#建立二維陣列
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [12]:
#會自動判斷最適合的型別
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [14]:
print('一維0矩陣')
print(np.zeros(10))
print('二維0矩陣')
print(np.zeros((3, 6)))
print('三維空矩陣')
print(np.empty((2, 3, 2)))

一維0矩陣
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
二維0矩陣
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
三維空矩陣
[[[  1.4005e-311   6.3660e-314]
  [  0.0000e+000   2.9644e-323]
  [  1.9098e-313   8.9334e+165]]

 [[  5.2660e-037   3.2255e-313]
  [  1.1167e+165   4.0318e-313]
  [  1.0414e-071   1.4213e+161]]]


In [18]:
print(np.arange(15))
print(np.arange(0, 10, 0.5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]


|函數名稱|說明|
|--|--|
|array|將輸入數據轉換成ndarray，預設值接複製輸入數字|
|asarray|將輸入數據轉換成ndarray，如果輸入本身就是ndarray就不進行複製|
|arange|類似內建的range，但是是ndarray物件不是list|
|ones|產生皆為1的陣列|
|zeros|產生皆為0的陣列|
|empty|產生空陣列|
|eye、identity|產生單元矩陣|

### Data Types for ndarrays
#### ndarray的數據類型

|類型|類型代碼|說明|
|--|--|--|
|int8, uint8|i1, u1|有正負和無正負的8位整數|
|int16, uint16|i2, u2|有正負和無正負的16位整數|
|int32, uint32|i4, u4|有正負和無正負的32位整數|
|int64, uint64|i8, u8|有正負和無正負的64位整數|
|float16|f2|半精度浮點數|
|float32|f4 or f|標準單精度浮點數|
|float64|f8 or d|標準雙精度浮點數|
|float128|f16 or g|擴展精度浮點數|
|complex64, complex128, complex256|c8, c16, c32|複數|
|bool|?|True與False|
|object|O|Python的物件|
|string\_|S|固定長度的字串，如S10表示10個字節的文字|
|unicode\_|U|固定長度的unicode類型，如U10表示10個字節的文字|


In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [23]:
#強迫轉換浮點數至整數，則小數部分捨去
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [24]:
#轉換文字至浮點數
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [26]:
#使用代碼宣告類型
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

### Operations between arrays and scalars

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

In [ ]:
1 / arr
arr ** 0.5

### Basic indexing and slicing

In [ ]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

In [ ]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr
arr_slice[:] = 64
arr

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [ ]:
arr2d[0][2]
arr2d[0, 2]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

#### Indexing with slices

In [ ]:
arr[1:6]

In [ ]:
arr2d
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]
arr2d[2, :1]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0

### Boolean indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
names
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'
data[-(names == 'Bob')]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### Fancy indexing

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

### Transposing arrays and swapping axes

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))